### ISSUE TITLE
hpcviewer doesn't select the right node when using flame

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#107]
When I tried hpcviewer 2021.05 on the FLASH database on MacOS, scalability loss analysis doesn't work the way it should. It selects one node too deep on the call path.

**Comment by laksono** [comment]
@jmellorcrummey :  Can you give me more detailed instructions to reproduce the bug? 
Mine works just fine:

![image](https://user-images.githubusercontent.com/8781032/134224812-70a50326-d7fe-4962-97f1-8d84786ba8d9.png)

**Comment by laksono** [comment]
Fixed in commit 3c28c0a57d010333781a2bbc347e3a4bd5edbd73

**Comment by laksono** [comment]
@jmellorcrummey can you please check if the fix works as intended? 
- If it works, can you please close the issue.
- If it doesn't, please specify the problems
