### ISSUE TITLE
Prof2 trace view (sometimes) doesn't render

### ISSUE THREAD

**Issue by blue42u** [laksono/hpcviewer.e4#117]
The trace view for some Prof2 databases does not render.

Seen on Linux (OpenJDK 11), develop branch.

To reproduce:
 1. Open [bug-no-trace-view.zip](https://github.com/HPCToolkit/hpcviewer.e4/files/7393705/bug-no-trace-view.zip) and open the trace view. Note that the trace view is simply blank, with a distorted left thread indicator bar:
![image](https://user-images.githubusercontent.com/17242663/138379084-fc6cf39b-640a-4f28-b892-9bda3bbaa7b3.png)
 2. Zoom in towards the middle of the view, note that the trace view is now visible:
![image](https://user-images.githubusercontent.com/17242663/138379129-390695d0-a10e-413c-a3ad-883e19746697.png)
 3. Zoom out all the way (home button), note that the thread indicator bar is distorted again and the rendered view has not updated:
![image](https://user-images.githubusercontent.com/17242663/138379218-08aeffab-4e93-499a-88d4-8a374fa374e0.png)

**Comment by laksono** [comment]
@blue42u There's something strange with the `experiment.xml` file: there are duplicates of ids:
```
<S i="76" s="78" l="369" it="76"/>
<C i="76" s="78" l="369" it="77">
```
Perhaps if we resolve this duplicates the problem disappears (I wish :-D

**Comment by blue42u** [comment]
I'm not sure why `i` would matter, since the traces are supposed to use the `it` attribute AFAIK.

I rewrote the Prof2 `experiment.xml` output to fix other trace issues, if I see this error again I'll reopen with a new database.
