### ISSUE TITLE
hot path in nattable

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#119]
When I used the flame button in the nattable implementation, I think the implementation could be improved just a bit. 

When I used it on the flash data, it moves the selection to the lowest node that it can following the 50% rule. That part is correct. What I would like as an enhancement is that if the node has children, the node be opened. The first thing I do when the hot path stops is look at the kids of the selected node. It should open the selected node automatically so I don't have to.

**Comment by laksono** [comment]
Which version do you use? 
It works fine with the viewer from the `develop` branch.

**Comment by laksono** [comment]
Duplicate with issue #107

**Comment by jmellorcrummey** [comment]
I checked the current version and it now works the way I want. thanks!
