### ISSUE TITLE
nattable: column header color on bottom-up and flat views

### ISSUE THREAD

**Issue by jmellorcrummey** [laksono/hpcviewer.e4#120]
The column headers for the metric pane on the bottom-up and flat view could be improved. On the top-down view, they are a light grey, which means that you can see the separator between the columns in the heading. On the bottom-up and flat view, the header background is the same color as the separator, so the separator is invisible. 

When you change the header color for the bottom-up and flat view, also change the color of the header labels from white to black (or whatever they are on the top-down view); the dark font is much more readable against the grey background.

**Comment by laksono** [comment]
The latest commit should fix this issue with both day and dark themes.
Day theme:

![image](https://user-images.githubusercontent.com/8781032/140762520-27cd8253-7f76-481e-8765-7f36ef56c649.png)

Dark theme:

![image](https://user-images.githubusercontent.com/8781032/140762568-f94ffa8b-616b-453e-8e24-3d07218a54f5.png)
