### ISSUE TITLE
nattable: limit to how much the scope column can be expanded 

### ISSUE THREAD

**Issue by aarontcopal2** [laksono/hpcviewer.e4#122]
With the develop version of hpcviewer, there are limits to how much I can expand the scope column. The column only expands up-to the width of the screen. I have long names in the scope column but cant scroll all the way to see the full name

**Comment by laksono** [comment]
This is the limitation of the current widget we use: we can't expand more than the width of the screen. To support horizontal scroll bar for tree column requires significant change (or at least that what I think).
At the moment, what you can do is to hover the mouse to show the "tooltip". Or another alternative is to have "copy-and-paste" feature.

**Comment by laksono** [comment]
Suggestion:
- scroll bar in the scope column
- pruning type names

**Comment by laksono** [comment]
This is related to fixed issue #199
