### ISSUE TITLE
Dualism of inline procedure: is it a proper procedure or not?

### ISSUE THREAD

**Issue by laksono** [laksono/hpcviewer.e4#129]
In the viewer, an inline procedure sometimes considers a proper function, but sometimes like a function body (something like loop). If it's both procedure and a function body, it causes confusion in the total cost.

For instance, in the top-down view we have `__GI__strcoll_l` calls inline function `[I] inlined from strcoll_l.c` and both has the same exclusive cost (`1.03e-04  33%`) and if we sum all the exclusive costs, it will be more than 100%.

![image](https://user-images.githubusercontent.com/8781032/139303487-221412b0-d486-40c1-b4da-f6aa22aa8e8e.png)

I think the inline procedure should be treated like a loop and shouldn't have the exclusive cost. 

Inline procedure on the bottom-up view (Extra):
![image](https://user-images.githubusercontent.com/8781032/139304715-dc83e6d0-be1f-46a0-856f-9f488e634151.png)

@jmellorcrummey any opinion?

**Comment by jmellorcrummey** [comment]
@laksono in this case, the notation "[i] inlined from ..." doesn't represent an inlined procedure. As @mwkrentel would say, this represents the "single alien" case where we see code from elsewhere, but we don't have a proper callsite for a proper inlined function. in such cases, i think we should treat these not as functions in the bottom-up view.

does that make sense?

**Comment by laksono** [comment]
Yup. That makes sense.
