### ISSUE TITLE
Color issues with profile view on GNOME dark theme

### ISSUE THREAD

**Issue by blue42u** [laksono/hpcviewer.e4#134]
Same vein as https://github.com/HPCToolkit/hpcviewer.e4/issues/127 and https://github.com/HPCToolkit/hpcviewer.e4/issues/132, related but not identical to either. Third time's the charm they say.

Below is a screenshot from GNOME 41 (specifically `gnome-shell` from Debian Unstable/Sid), "Adwaita-dark" theme:
![image](https://user-images.githubusercontent.com/17242663/139793880-22c55b0e-5f85-4a57-bfc8-55d7aa09ae81.png)

It should be obvious, but this looks *really ugly*. It improved a bit after 2004ca68d7bb273070de6f3bac81e625e7c2ed97 but it could still use some work. Specifically:
 - The background color doesn't paint to the edges of the widget, which gives a poor visual effect (it seems to "melt" into the surrounding window, esp. without a border). Same goes for the selected row coloration.
 - The grey used for metric values and non-hyperlink functions is dang hard to read on the black background. Using white (like `170:`) would be a much better choice here. Same goes for the headers (although they seem to be slightly lighter gray).
 - The altered background header for the selected metric column looks really out of place, and the text is even more difficult to read. IMO just the chevron (in an appropriate color) is enough of an indicator.
 - The gray for the selected row coloration somehow clashes with every other color on the line, especially the cyan `520:`. It's not a good color, neither is the cyan (which doesn't look great on the black either).
 - The blue line marking the leftmost metric column is *really* hard to see against the black background, and its high contrast with the white horizontal rules causes something like an optical illusion.
 - The pure-black background is far too dark to look good, especially with text in front it tends to make the text difficult to read. IMO a dark grey would do much better.

The blue for function names and tan(?) for "Aggregate Metrics" seem relatively fine, but IMO pretty much all of the colors otherwise need to be changed.

For inspiration, my terminal (`gnome-terminal`, system theme + Tango palette) looks like the following. I find it very readable even at the 90% opacity I usually run at.
![image](https://user-images.githubusercontent.com/17242663/139796097-be3f53a2-2082-4900-a208-f16f9093a493.png)

IMO the Viewer palette should be 5 colors: background (dark grey), border + rules (just light enough grey to contrast), selected row (contrasting light grey or light desaturated blue), most text (white or off-white), and link-type text (dark-ish blue). Maybe an extra color to distinguish file/line numbers from functions (dark-ish green might work well). I also think the "Aggregate Metrics" row doesn't need to be specially colored, a mild visual separation from the headers would suffice (wider rule + bit of extra vertical spacing).

**Comment by blue42u** [comment]
After the new commits this is looking better:
![image](https://user-images.githubusercontent.com/17242663/140937053-e4ebe436-f89e-41ce-a7ff-49526bec612a.png)
Many of my issues are still present but the critical readability problems have been resolved: The text/background colors are much better and readable (although the aliasing isn't kind to the off-cyan `520:` or `18:`). The blue edge is still contrasting too much with the white horizontal bars (which causes the optical illusion effect). The colors are the same or aren't drawn to the edge of the widget (giving the "melting" effect into the surrounding window). The selected row/column color cause readability issues, but IMO it's not a striking color among the other grays and could use some hue.

**Comment by laksono** [comment]
@blue42u  Thanks a lot for looking carefully for this issue. I am not sure if we have time to completely fix this before SC21 since there are other critical issues need to be fixed first.
NatTable widget has tons of knobs and it takes time to find which one needs to be set. For instance the blue edge is configured somewhere under NatTable classes. The trick is to hunt where it is set and how to override it.
We can revisit again this issue after SC21.

**Comment by laksono** [comment]
Suggestion:
- swap the icon of callsite and the text

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/134)
