### ISSUE TITLE
hpcviewer.e4 develop corrupts when opening a prof2 database

### ISSUE THREAD

**Issue by Jokeren** [laksono/hpcviewer.e4#152]
[hpctoolkit-PeleC3d.gnu.CUDA.ex-database.tar.gz](https://github.com/HPCToolkit/hpcviewer.e4/files/7798514/hpctoolkit-PeleC3d.gnu.CUDA.ex-database.tar.gz)

It was fine when I built develop back in 2021.10

**Comment by laksono** [comment]
Can you be more specific? What is the error message? How to reproduce the error?
I tried with the latest develop branch, it works just fine.

![image](https://user-images.githubusercontent.com/8781032/147865551-9908ae0f-22e8-497e-8a13-7b729fd578b5.png)

**Comment by Jokeren** [comment]
@laksono That's weird, I just checked out the develop branch and built it. I was using the x86_64 version.
Here's the error message. 
![image](https://user-images.githubusercontent.com/2306281/147865751-17e6359d-9040-49fb-89cf-118f4154df71.png)

**Comment by laksono** [comment]
Can you send me the size of the files in the directory?
Mine (on x86_64 as well but not on ufront):
```
-rw-r--r-- 1 la5 la5 35899116 Jan  1 21:32 cct.db
-rw-r--r-- 1 la5 la5  6784541 Jan  1 21:32 experiment.xml
-rw-r--r-- 1 la5 la5    16015 Jan  1 21:32 FORMATS.md
-rw-r--r-- 1 la5 la5 25735748 Jan  1 21:32 profile.db
drwxr-xr-x 4 la5 la5     4096 Jan  1 21:32 src
-rw-r--r-- 1 la5 la5      172 Jan  1 21:32 trace.db
```

**Comment by Jokeren** [comment]
-rw-r--r--. 1 kz21 users 35899116 Jan  1 21:32 cct.db
-rw-r--r--. 1 kz21 users  6784541 Jan  1 21:32 experiment.xml
-rw-r--r--. 1 kz21 users    16015 Jan  1 21:32 FORMATS.md
-rw-r--r--. 1 kz21 users 25735748 Jan  1 21:32 profile.db
drwxr-xr-x. 4 kz21 users     4096 Jan  1 21:32 src
-rw-r--r--. 1 kz21 users      172 Jan  1 21:32 trace.db

**Comment by Jokeren** [comment]
@laksono FYI, it is probably not a software issue but instead a build issue. I built a working version on gpu.cs using the same code.

**Comment by laksono** [comment]
@Jokeren Is there any error message during the build? Which java version did you use?
I just built on ufront and it worked just fine.

**Comment by Jokeren** [comment]
I was using openjdk-11.0.8_10. I didn't observe any build errors.
