### ISSUE TITLE
RFE: List properties of the selected function block

### ISSUE THREAD

**Issue by blue42u** [laksono/hpcviewer.e4#172]
It would be helpful when analyzing a trace if the start/duration times of the function block under the cursor were listed in the cursor line (currently you have to zoom in far on each endpoint and record the numbers yourself). These times should use an appropriate unit (eg. `100ms` not `0.1s`), falling back to `hh:mm:ss.sss` for very large values. The precision should (probably) be configurable (unless 9 digits past the decimal is still small enough to fit in the line).

IMHO this should only consider the function block **as rendered**, so if there's a 1-sample break it will still consider it one block. If this is considered two blocks instead, the "real" block under the cursor should be highlighted.

Motivating example:
![image](https://user-images.githubusercontent.com/17242663/151834201-cb5f1b38-bddb-4998-9e07-4edfe1a83c55.png)

Here I would like the cursor line to read:
```
... Cross hair: (1,482ms, Thread 0) Duration: 710.035ms Start: 1.538s
```

**Comment by laksono** [comment]
Good point. This is really useful.

**Comment by blue42u** [comment]
[This repository has moved to GitLab, please continue this issue there.](https://gitlab.com/hpctoolkit/hpcviewer/-/issues/172)
