### ISSUE TITLE
Default metric column width not derived from metric font

### ISSUE THREAD

**Issue by blue42u** [laksono/hpcviewer.e4#203]
**Describe the bug**
The default metric column width appears to be derived using the "default column font," not the "metric column font." In cases where the former is narrower than the latter, this causes metric values to end up clipped by default.

**To Reproduce**
1. Decrease the default column font size by a few points:
   ![image](https://user-images.githubusercontent.com/17242663/170830315-ccb62bc8-dae8-4bd2-93d1-f0209deb1e40.png)

2. Apply and switch back to the profile view (and/or close and re-open the database). Note that the metric values are now clipped because of the default column width:
   ![image](https://user-images.githubusercontent.com/17242663/170830322-9a449dc2-c61a-4671-8902-555f27dddeb6.png)

3. Adjust the metric column font to match the default column font:
   ![image](https://user-images.githubusercontent.com/17242663/170830381-93242bc1-ac61-4312-9477-a9ac37562f11.png)

4. Apply and switch back to the profile view (and/or close and re-open the database). Note that the metric values are no longer clipped, even though the column width has not changed:
   ![image](https://user-images.githubusercontent.com/17242663/170830423-bd68cffd-8db5-4300-a1eb-cf8428feb4c5.png)

**Expected behavior**
The default metric column width should be derived using the metric column font, so that the metric values are never clipped by default.

**Platform**
 - OS: Linux (Debian, GNOME 42)
 - Architecture: x86_64
 - Version: `master` (c3c7b63a53fa56b9cefa9f6d009a356d853e6685)

**Comment by laksono** [comment]
@blue42u I still cannot reproduce the issue, even on Linux. 

![image](https://user-images.githubusercontent.com/8781032/171228894-0f154745-4752-4311-b305-6d7ded2b4990.png)

**Comment by blue42u** [comment]
Hrm. Is there any other system information I can provide that would help? I'm running on Java 11.0.15.

**Comment by laksono** [comment]
Well, Java is not the issue.
Can you reproduce the problem on any CS machine? Like iris or ufront?

**Comment by blue42u** [comment]
I can reproduce on both iris and ufront, if I copy my locally-built Viewer package over (I don't have Maven set up on those machines).

**Comment by laksono** [comment]
This is frustrating. I still can't reproduce it on iris.
