### ISSUE TITLE
meta.db: Entry points need adjustment

### ISSUE THREAD

**Issue by blue42u** [laksono/hpcviewer.e4#230]
1. Entry points are currently named by the "canonical name" listed in the `pPrettyName` field. These names are intended for forward-compatibility cases. They are designed to be human-readable but only within the context of an entry point, having them "loose" like this is confusing.
 2. Entry points are shown in the bottom-up and flat views. Even more confusingly they end up merged into a single row with 100% cost, with an arbitrary name in the scope column.

**To Reproduce**
Occurs in all multithreaded `meta.db` databases.

**Expected behavior**
Entry points should be named with names befitting their context:
 - When possible a proper name should be generated based on the `entryPoint` field (e.g. `(entryPoint: 1)` maps to `<program root>`).
 - If the `entryPoint` is unrecognized the `pPrettyName` should be housed in symbols to differentiate it from regular contexts (e.g. `<entry: main thread>`).

Entry points should not be present in any view besides the top-down view (and trace view).

**Screenshots**
![image](https://user-images.githubusercontent.com/17242663/180862266-bdd104d1-b4c8-46a2-b461-f2c7490759d9.png)
![image](https://user-images.githubusercontent.com/17242663/180862366-2fe8dcf4-dec2-4eb4-80bc-0216588ccd9f.png)
![image](https://user-images.githubusercontent.com/17242663/180862438-b79994b4-e3ca-4843-8903-bd96a4dbbd47.png)

**Platform (please complete the following information):**
 - OS: Linux
 - Architecture: x86_64
 - Version: Current `develop` (https://github.com/HPCToolkit/hpcviewer.e4/commit/ade248d3ba182939c472019f81455913b31eb965)

**Comment by laksono** [comment]
Fixed in commit d06c2a3263b2c699956b3a6c12f65a73b54288a1
